title: MTG Summit 2022
dates: 18-19 Mars
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "/event-template" # the subpath of your site, e.g. /blog
url: "https://mtg-x.github.io" # the base hostname & protocol for your site

#navigation
navigationLinks:
 - {url: "/", text: "Accueil"}
 - {url: "/agenda/", text: "Agenda"}
 - {url: "/speakers/", text: "Speakers"}
 - {url: "/team/", text: "Participants"}
 - {url: "/faq/", text: "FAQ"}
 - {url: "/coc/", text: "CoC"}
 - {url: "/sponsors/", text: "Communautés"}

pageHeaders:
  agenda: {bg: "#00a1f1", font: "#fff", title: "Agenda"}
  speakers: {bg: "#f65314", font: "#fff", title: "Speakers"}
  team: {bg: "#7cbb00", font: "#fff", title: "Participants"}
  faq: {bg: "#ffbb00", font: "#fff", title: "Foire Aux Questions"}
  coc: {bg: "#f65314", font: "#fff", title: "Code de Conduite"}
  sessions: {bg: "#7cbb00", font: "#fff"}
  sponsors: {bg: "#ffbb00", font: "#fff", title: "Communautés"}
  statistics: {bg: "#7cbb00", font: "#fff"}
  
  
collections:
  sessions:
    output: true
    permalink: /sessions/:title

defaults:
  -
    scope:
      path: ""
      type: "sessions"
    values:
      layout: "session"
      css: agenda

logo: "../css/style/img/icon-large.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-datapage-generator

page_gen-dirs: false

page_gen:
  - data: 'speakers'
    template: 'speaker'
    name: 'id'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/c/MUGTVFrance
  - title: twitter
    url: https://twitter.com/msdev_fr

share:
  - platform: twitter
    url: "https://twitter.com/share?url=%2f&text="
    text: "I am at the %23MTGSummit and it is awesome!"

# Build settings
markdown: kramdown
permalink: pretty