title: MTG:France
dates: 18-19 Mars
description: > # this means to ignore newlines until "baseurl:"
  Association Microsoft Tech Group France
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mtg-france.org" # the base hostname & protocol for your site

#navigation
navigationLinks:
  - { url: "/", text: "Accueil" }
  #- {url: "/agenda/", text: "Agenda"}
  #- {url: "/speakers/", text: "Speakers"}
  - {url: "/team/", text: "Team"}
  #- {url: "/faq/", text: "FAQ"}
  - {url: "/coc/", text: "CoC"}
  - {url: "/sponsors/", text: "Communautés"}
  - {url: "/events/", text: "Events"}

pageHeaders:
  agenda: { bg: "#00a1f1", font: "#fff", title: "Agenda" }
  speakers: { bg: "#f65314", font: "#fff", title: "Speakers" }
  team: { bg: "#7cbb00", font: "#fff", title: "Team" }
  faq: { bg: "#ffbb00", font: "#fff", title: "Foire Aux Questions" }
  coc: { bg: "#f65314", font: "#fff", title: "Code de Conduite" }
  sessions: { bg: "#7cbb00", font: "#fff" }
  sponsors: { bg: "#ffbb00", font: "#fff", title: "Communautés" }
  events: { bg: "#ffbb00", font: "#fff", title: "Events" }
  statistics: { bg: "#7cbb00", font: "#fff" }

collections:
  sessions:
    output: true
    permalink: /sessions/:title

defaults:
  - scope:
      path: ""
      type: "sessions"
    values:
      layout: "session"
      css: agenda

logo: "../css/style/img/icon-large.png"

#google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ["pages"]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-datapage-generator

page_gen-dirs: false

page_gen:
  - data: "speakers"
    template: "speaker"
    name: "id"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UCIuBHEwIFRjwRMm9--Ga1vg
  - title: linkedin
    url: https://www.linkedin.com/company/mtg-france
  - title: twitter
    url: https://twitter.com/MTG_France_org

share:
  - platform: twitter
    url: "https://twitter.com/share?url=%2f&text="
    text: "Hey %23MTG_France_org!"

# Build settings
markdown: kramdown
permalink: pretty
